name: Build RPMs and submit to COPR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  submit:
    # Specify the runner
    runs-on: ubuntu-latest

    # Run the job inside a Fedora container
    container:
      image: fedora:42

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Install Required Packages
      - name: Install Required Packages
        run: |
          # Update the package index
          dnf -y update

          # Install RPM build tools and dependencies
          dnf install -y rpm-build rpmdevtools dnf-plugins-core copr-cli

          # Install 'builddep' command for DNF
          dnf install -y 'dnf-command(builddep)'

          # Set up RPM build environment
          rpmdev-setuptree

      # Copy Spec and Source Files
      - name: Copy Spec and Source Files
        run: |
          # Copy xremap.spec to SPECS directory
          cp xremap.spec ~/rpmbuild/SPECS/

          # Copy 00-xremap-input.rules to SOURCES directory
          cp 00-xremap-input.rules ~/rpmbuild/SOURCES/

      # Download the Source Tarball
      - name: Download Source Tarball
        run: |
          cd ~/rpmbuild/SPECS

          # Download sources defined in the spec file
          spectool -g -R xremap.spec

      # Build the SRPM
      - name: Build the Source RPM (SRPM)
        run: |
          cd ~/rpmbuild/SPECS

          # Build the SRPM
          rpmbuild -bs xremap.spec

      # Upload SRPM as Artifact
      - name: Upload SRPM
        uses: actions/upload-artifact@v4
        with:
          name: srpm
          path: |
            ~/rpmbuild/SRPMS/*.src.rpm

      - name: Configure copr-cli
        run: |
          mkdir -p ~/.config
          echo "[copr-cli]" > ~/.config/copr
          echo "login = ${{ secrets.COPR_LOGIN }}" >> ~/.config/copr
          echo "username = blakegardner" >> ~/.config/copr
          echo "token = ${{ secrets.COPR_TOKEN }}" >> ~/.config/copr
          echo "copr_url = https://copr.fedorainfracloud.org" >> ~/.config/copr
          
      - name: Install build dependencies
        run: |
          cd ~/rpmbuild/SPECS
          dnf builddep -y xremap.spec

      - name: Build RPM packages locally
        run: |
          cd ~/rpmbuild/SPECS
          
          # Build all RPM variants
          rpmbuild -bb xremap.spec
          
          # List built RPMs
          ls -la ~/rpmbuild/RPMS/*/

      # - name: Submit Source RPM to COPR
      #   run: |
      #     copr-cli build blakegardner/xremap ~/rpmbuild/SRPMS/xremap-*.src.rpm

      - name: Upload RPMs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ~/rpmbuild/SRPMS/*.src.rpm
            ~/rpmbuild/RPMS/*/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
